// AI Task Customization Service
// Generates context-specific tasks using Claude or OpenAI API based on questionnaire responses

const CLAUDE_API_URL = 'https://api.anthropic.com/v1/messages';
const OPENAI_API_URL = 'https://api.openai.com/v1/chat/completions';

/**
 * Detect which AI provider to use based on available API keys
 * @returns {Object} { provider: 'claude'|'openai'|null, key: string|null }
 */
function detectProvider() {
  const claudeKey = import.meta.env.VITE_CLAUDE_API_KEY;
  const openaiKey = import.meta.env.VITE_OPENAI_API_KEY;

  if (claudeKey) {
    return { provider: 'claude', key: claudeKey };
  }
  if (openaiKey) {
    return { provider: 'openai', key: openaiKey };
  }
  return { provider: null, key: null };
}

/**
 * Generate AI-customized tasks for a specific phase
 * @param {Object} responses - All questionnaire responses
 * @param {string} phase - 'clarity', 'implementation', or 'adoption'
 * @returns {Promise<Array>} Array of AI-generated tasks
 */
export async function generateCustomTasks(responses, phase) {
  const { provider, key } = detectProvider();

  if (!provider) {
    console.warn('No AI API key provided (Claude or OpenAI). Skipping AI customization.');
    return [];
  }

  console.log(`Using ${provider.toUpperCase()} for AI task generation`);

  try {
    const context = buildContext(responses);
    const prompt = buildPrompt(context, phase, responses.language || 'English');

    // Show user how AI uses questionnaire data
    console.log(`\n📋 AI PROMPT FOR ${phase.toUpperCase()} PHASE:`);
    console.log('━'.repeat(80));
    console.log(prompt);
    console.log('━'.repeat(80));
    console.log('👆 This prompt shows how your questionnaire answers are used by AI\n');

    let tasks;
    if (provider === 'claude') {
      tasks = await generateWithClaude(key, prompt);
    } else if (provider === 'openai') {
      tasks = await generateWithOpenAI(key, prompt);
    }

    if (!tasks || tasks.length === 0) {
      console.warn(`No tasks generated by ${provider}`);
      return [];
    }

    console.log(`✅ Successfully parsed ${tasks.length} tasks from ${provider}`);

    // Add metadata to tasks
    return tasks.map(task => ({
      ...task,
      task_type: 'ai_generated',
      phase: phase.charAt(0).toUpperCase() + phase.slice(1),
      tags: Array.isArray(task.tags) ? task.tags : [task.tags || phase],
      ai_provider: provider
    }));

  } catch (error) {
    console.error('Error generating AI tasks:', error);
    return [];
  }
}

/**
 * Generate tasks using Claude API
 */
async function generateWithClaude(apiKey, prompt) {
  const response = await fetch(CLAUDE_API_URL, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': apiKey,
      'anthropic-version': '2023-06-01'
    },
    body: JSON.stringify({
      model: 'claude-3-5-sonnet-20241022',
      max_tokens: 2000,
      messages: [{
        role: 'user',
        content: prompt
      }]
    })
  });

  if (!response.ok) {
    const errorText = await response.text();
    console.error('Claude API error:', response.status, errorText);
    return [];
  }

  const data = await response.json();
  const tasksText = data.content[0].text;

  console.log('\n🔍 RAW CLAUDE RESPONSE:');
  console.log('━'.repeat(80));
  console.log(tasksText);
  console.log('━'.repeat(80));

  return extractTasksFromJSON(tasksText);
}

/**
 * Generate tasks using OpenAI API
 */
async function generateWithOpenAI(apiKey, prompt) {
  const response = await fetch(OPENAI_API_URL, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${apiKey}`
    },
    body: JSON.stringify({
      model: 'gpt-4-turbo-preview',
      messages: [{
        role: 'system',
        content: 'You are an expert Odoo implementation consultant. Return a JSON object with a "tasks" array containing task objects. Each task must have: name, description, estimated_hours (integer), priority, category, tags (array).'
      }, {
        role: 'user',
        content: prompt
      }],
      temperature: 0.7,
      max_tokens: 2000,
      response_format: { type: 'json_object' }
    })
  });

  if (!response.ok) {
    const errorText = await response.text();
    console.error('OpenAI API error:', response.status, errorText);
    return [];
  }

  const data = await response.json();
  const tasksText = data.choices[0].message.content;

  console.log('\n🔍 RAW OPENAI RESPONSE:');
  console.log('━'.repeat(80));
  console.log(tasksText);
  console.log('━'.repeat(80));

  return extractTasksFromJSON(tasksText);
}

/**
 * Extract JSON array from AI response text
 */
function extractTasksFromJSON(text) {
  try {
    console.log('🔄 Parsing AI response...');

    // First try to parse as direct JSON
    const parsed = JSON.parse(text);
    console.log('✅ JSON parsed successfully. Type:', Array.isArray(parsed) ? 'array' : 'object');

    let tasksArray = [];

    // If it's an object with a tasks property, use that
    if (parsed.tasks && Array.isArray(parsed.tasks)) {
      console.log(`✅ Found 'tasks' array with ${parsed.tasks.length} items`);
      tasksArray = parsed.tasks;
    }
    // If it's already an array, use it
    else if (Array.isArray(parsed)) {
      console.log(`✅ Response is already an array with ${parsed.length} items`);
      tasksArray = parsed;
    }
    // Try to find any array property in the object
    else if (typeof parsed === 'object') {
      console.log('🔍 Searching for array properties in object...');
      for (const [key, value] of Object.entries(parsed)) {
        if (Array.isArray(value)) {
          console.log(`✅ Found array property '${key}' with ${value.length} items`);
          tasksArray = value;
          break;
        }
      }
    }

    if (tasksArray.length === 0) {
      console.error('❌ No task array found in response');
      console.log('Parsed object keys:', Object.keys(parsed));
      return [];
    }

    // Validate and normalize each task
    console.log(`🔍 Validating ${tasksArray.length} tasks...`);
    const validTasks = tasksArray.map((task, index) => {
      console.log(`Task ${index + 1}:`, task);

      // Ensure required fields exist
      const normalizedTask = {
        name: task.name || task.title || task.task || `Unnamed Task ${index + 1}`,
        description: task.description || task.desc || '',
        estimated_hours: parseInt(task.estimated_hours || task.hours || task.duration || 4),
        priority: task.priority || 'Medium',
        category: task.category || task.type || 'Custom Development',
        tags: Array.isArray(task.tags) ? task.tags : (task.tags ? [task.tags] : ['Custom'])
      };

      console.log(`  ✅ Normalized:`, normalizedTask);
      return normalizedTask;
    });

    console.log(`✅ Successfully validated ${validTasks.length} tasks`);
    return validTasks;

  } catch (error) {
    console.error('❌ Error parsing AI response:', error);
    console.error('Raw text:', text);
    return [];
  }
}

/**
 * Build context object from questionnaire responses
 */
function buildContext(responses) {
  // Build custom modules array
  const customModules = [];
  const customModulesCount = parseInt(responses.custom_modules_count) || 0;
  for (let i = 1; i <= customModulesCount; i++) {
    const name = responses[`custom_module_${i}_name`];
    const hours = responses[`custom_module_${i}_hours`];
    if (name) {
      customModules.push({ name, hours: parseInt(hours) || 0 });
    }
  }

  return {
    // Project basics
    industry: responses.industry || 'General',
    country: responses.country || '',
    language: responses.language || 'English',

    // Hour budgets
    clarity_hours: responses.clarity_hours || 40,
    implementation_hours: responses.implementation_hours || 100,
    adoption_hours: responses.adoption_hours || 20,

    // Custom modules
    custom_modules: customModules,
    custom_modules_count: customModulesCount,

    // Clarity phase context
    current_systems: responses.current_systems || '',
    pain_points: responses.pain_points || '',
    core_processes: responses.core_processes || '',

    // Implementation context
    modules: responses.modules || [],
    data_migration: responses.data_migration || 'No',
    data_migration_scope: responses.data_migration_scope || '',
    integrations: responses.integrations || 'No',
    integration_list: responses.integration_list || '',
    customization_scope: responses.customization_scope || '',
    multi_company: responses.multi_company || 'No',
    company_count: responses.company_count || 1,
    multi_warehouse: responses.multi_warehouse || 'No',
    warehouse_count: responses.warehouse_count || 1,

    // Adoption context
    user_count: responses.user_count || 0,
    user_breakdown: responses.user_breakdown || '',
    training_format: responses.training_format || 'Hybrid',
  };
}

/**
 * Get example task names based on language
 */
function getExamples(language) {
  const isSpanish = language === 'Spanish' || language === 'Español';

  return {
    clarity: {
      name: isSpanish
        ? "Mapear proceso específico desde [sistema actual]"
        : "Map specific process from [current system]",
      description: isSpanish
        ? "Descripción detallada"
        : "Detailed description",
      category: isSpanish
        ? "Mapeo de Procesos"
        : "Process Mapping",
      tags: isSpanish
        ? ["Claridad", "Descubrimiento"]
        : ["Clarity", "Discovery"]
    },
    migration: {
      name: isSpanish
        ? "Migración de datos desde [sistema] a Odoo"
        : "Data migration from [system] to Odoo",
      description: isSpanish
        ? "Plan detallado de migración"
        : "Detailed migration plan",
      category: isSpanish
        ? "Migración de Datos"
        : "Data Migration",
      tags: isSpanish
        ? ["Implementación", "Migración"]
        : ["Implementation", "Migration"]
    },
    customModule: {
      nameTemplate: (moduleName) => isSpanish
        ? `${moduleName} - Diseño de estructura de base de datos`
        : `${moduleName} - Database structure design`,
      description: isSpanish
        ? "Diseñar estructura de base de datos con SKU, fabricante, especificaciones"
        : "Design database structure with SKU, manufacturer, specs",
      category: isSpanish
        ? "Desarrollo Personalizado"
        : "Custom Development",
      tags: isSpanish
        ? ["Implementación", "Desarrollo"]
        : ["Implementation", "Development"],
      subtasks: (moduleName) => isSpanish ? [
        `${moduleName} - Diseño de estructura de base de datos`,
        `${moduleName} - Configuración de campos específicos`,
        `${moduleName} - Integración con otros módulos`,
        `${moduleName} - Dashboard de análisis`,
        `${moduleName} - Testing e integración`
      ] : [
        `${moduleName} - Database structure design`,
        `${moduleName} - Configure specific fields`,
        `${moduleName} - Integration with other modules`,
        `${moduleName} - Analysis dashboard`,
        `${moduleName} - Testing and integration`
      ]
    },
    adoption: {
      training: isSpanish
        ? "Capacitación para el equipo de [área]"
        : "Training for [area] team",
      changeManagement: isSpanish
        ? "Taller de gestión del cambio"
        : "Change management workshop",
      documentation: isSpanish
        ? "Creación de documentación y guías"
        : "Documentation and guide creation",
      category: isSpanish
        ? "Capacitación"
        : "Training",
      tags: isSpanish
        ? ["Adopción", "Capacitación"]
        : ["Adoption", "Training"]
    }
  };
}

/**
 * Build AI prompt based on phase and context
 */
function buildPrompt(context, phase, language) {
  const examples = getExamples(language);
  const isSpanish = language === 'Spanish' || language === 'Español';

  const baseInstructions = `You are an expert Odoo implementation consultant at Arkode.

CRITICAL LANGUAGE REQUIREMENT:
- ALL task names MUST be in ${language} language
- ALL descriptions MUST be in ${language} language
- ALL categories MUST be in ${language} language
- ALL tags MUST be in ${language} language
- NO mixing of languages - maintain consistency throughout

CRITICAL RULES:
- Return ONLY a valid JSON object with a "tasks" array - NO other text before or after
- Estimated hours must be whole numbers only (no decimals)
- Each task must have: name, description, estimated_hours, priority, category, tags (array)
- For custom module tasks, include "custom_module" field with the exact module name

Context:
Industry: ${context.industry}
Country: ${context.country}
Modules: ${context.modules.join(', ')}
`;

  if (phase === 'clarity') {
    return `${baseInstructions}
Current Systems: ${context.current_systems}
Pain Points: ${context.pain_points}
Core Processes: ${context.core_processes}

TASK: Generate 2-3 specific Clarity phase discovery tasks ONLY.

BUDGET CONSTRAINT: Total hours for ALL tasks must NOT exceed ${Math.round(context.clarity_hours * 0.3)} hours (30% of Clarity budget is for AI tasks, rest is template).

Focus on:
- Specific process mapping from current systems mentioned
- Workshops addressing the exact pain points listed
- Discovery sessions for the core processes described

DO NOT generate generic tasks. Use the specific systems, pain points, and processes mentioned above.

Return format (example in ${language}):
{
  "tasks": [
    {
      "name": "${examples.clarity.name}",
      "description": "${examples.clarity.description}",
      "estimated_hours": 6,
      "priority": "${isSpanish ? 'Alta' : 'High'}",
      "category": "${examples.clarity.category}",
      "tags": ${JSON.stringify(examples.clarity.tags)}
    }
  ]
}`;
  }

  if (phase === 'implementation') {
    // Calculate available hours for AI tasks (custom dev portion)
    const customDevBudget = Math.round(context.implementation_hours * 0.5); // 50% for custom work

    // Build custom modules description
    let customModulesDescription = 'None';
    if (context.custom_modules && context.custom_modules.length > 0) {
      customModulesDescription = context.custom_modules.map((mod, idx) =>
        `${idx + 1}. ${mod.name} (${mod.hours}h allocated)`
      ).join('\n');

      if (context.customization_scope) {
        customModulesDescription += '\n\nDetailed Requirements:\n' + context.customization_scope;
      }
    } else if (context.customization_scope) {
      customModulesDescription = context.customization_scope;
    }

    return `${baseInstructions}
Data Migration Scope: ${context.data_migration_scope || 'None'}
Integration Requirements: ${context.integration_list || 'None'}

Custom Modules to Develop:
${customModulesDescription}

Multi-company: ${context.multi_company} ${context.multi_company === 'Yes' ? `(${context.company_count} companies)` : ''}
Multi-warehouse: ${context.multi_warehouse} ${context.multi_warehouse === 'Yes' ? `(${context.warehouse_count} warehouses)` : ''}

TASK: Generate specific Implementation tasks for DATA MIGRATION and CUSTOM MODULES.

BUDGET CONSTRAINT: Total hours for ALL tasks must NOT exceed ${customDevBudget} hours.

IMPORTANT - Generate tasks ONLY for:
1. Data migration from systems mentioned (if scope provided)
2. Custom modules listed above - break down each module into subtasks
3. Third-party integrations listed (if any)

DO NOT generate tasks for:
- Standard Odoo module configuration (CRM, Sales, etc.) - templates handle this
- Training or user adoption - that's the Adoption phase
- Generic setup tasks

CRITICAL - Task naming requirements:
- Use the EXACT module names provided above
- Break down each custom module into 3-5 subtasks
- Example subtask names in ${language}:
${examples.customModule.subtasks('I+D Module').map((s, i) => `  * "${s}" (${15 + i * 5}h)`).join('\n')}

Each task should be 15-40 hours maximum.

Return format (example in ${language}):
{
  "tasks": [
    {
      "name": "${examples.migration.name}",
      "description": "${examples.migration.description}",
      "estimated_hours": 30,
      "priority": "${isSpanish ? 'Alta' : 'High'}",
      "category": "${examples.migration.category}",
      "tags": ${JSON.stringify(examples.migration.tags)}
    },
    {
      "name": "${examples.customModule.nameTemplate('I+D Module')}",
      "description": "${examples.customModule.description}",
      "estimated_hours": 16,
      "priority": "${isSpanish ? 'Alta' : 'High'}",
      "category": "${examples.customModule.category}",
      "tags": ${JSON.stringify(examples.customModule.tags)},
      "custom_module": "I+D Module"
    }
  ]
}

IMPORTANT: For each custom module task, include the "custom_module" field with the EXACT module name from the list above.`;
  }

  if (phase === 'adoption') {
    return `${baseInstructions}
User Count: ${context.user_count}
User Breakdown: ${context.user_breakdown}
Training Format: ${context.training_format}

TASK: Generate 2-4 specific Adoption phase tasks focused on TRAINING and CHANGE MANAGEMENT only.

BUDGET CONSTRAINT: Total hours for ALL tasks must NOT exceed ${Math.round(context.adoption_hours * 0.5)} hours (50% of Adoption budget).

CRITICAL - Generate tasks ONLY for:
1. Role-based training sessions for user groups mentioned
2. Change management workshops
3. Documentation creation
4. Go-live support planning

DO NOT generate tasks for:
- Building features or modules (that's Implementation phase!)
- Configuring integrations (that's Implementation phase!)
- Data migration (that's Implementation phase!)
- System development (that's Implementation phase!)

Focus on how to TRAIN users on the already-built system, NOT on building new features.

Example of CORRECT Adoption tasks in ${language}:
- "${examples.adoption.training.replace('[área]', isSpanish ? 'ventas' : 'sales')}" (8h)
- "${examples.adoption.changeManagement}" (4h)
- "${examples.adoption.documentation}" (6h)

Example of WRONG Adoption tasks (these are Implementation phase, not Adoption!):
- "${isSpanish ? 'Integración de inventario en tiempo real' : 'Real-time inventory integration'}" ❌
- "${isSpanish ? 'Sistema de geolocalización' : 'Geolocation system'}" ❌
- "${isSpanish ? 'Dashboard de rentabilidad' : 'Profitability dashboard'}" ❌

Return format (example in ${language}):
{
  "tasks": [
    {
      "name": "${examples.adoption.training}",
      "description": "${isSpanish ? 'Detalles de la sesión de capacitación' : 'Training session details'}",
      "estimated_hours": 8,
      "priority": "${isSpanish ? 'Alta' : 'High'}",
      "category": "${examples.adoption.category}",
      "tags": ${JSON.stringify(examples.adoption.tags)}
    }
  ]
}`;
  }

  return baseInstructions + '\nReturn only the JSON object with tasks array.';
}

/**
 * Check if AI customization is available
 * @returns {Object} { available: boolean, provider: 'claude'|'openai'|null }
 */
export function getAICustomizationStatus() {
  const { provider } = detectProvider();
  return {
    available: !!provider,
    provider: provider
  };
}
